### ISSUE TITLE
Get Crisp Chat Applet in Production

### ISSUE THREAD

**Issue by VonSub** [freeflowpages/freeflow-theme#1]
Get the new Crips Chat app into: https://freeflowpages.com/user/auth/login

html snippet that needs to go into the head:

<script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="1a5a5241-91cb-4a41-8323-5ba5ec574da0";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

**Comment by PeterNashaat** [comment]
- Added to staging , will be migrated to production next sunday

**Comment by VonSub** [comment]
@PeterNashaat update?
